import { pgTable, uuid, varchar, integer, decimal, timestamp, date, pgEnum, jsonb, boolean, time } from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';
import { users } from './users';
import { subjects } from './subjects';

// Enums
export const studyTaskStatusEnum = pgEnum('study_task_status', ['pending', 'completed', 'skipped', 'rescheduled']);
export const riskLevelEnum = pgEnum('risk_level', ['low', 'medium', 'high']);
export const recommendationTypeEnum = pgEnum('recommendation_type', ['lesson', 'quiz', 'review_document', 'study_habit']);
export const challengeTypeEnum = pgEnum('challenge_type', ['daily', 'weekly']);
export const relationTypeEnum = pgEnum('relation_type', ['parent', 'teacher']);

// 1. Student Profiles
export const studentProfiles = pgTable('student_profiles', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').references(() => users.id, { onDelete: 'cascade' }).notNull().unique(),
  currentLevel: integer('current_level').default(1).notNull(),
  xp: integer('xp').default(0).notNull(),
  dailyStudyGoalMinutes: integer('daily_study_goal_minutes').default(30).notNull(),
  targetGrade: varchar('target_grade', { length: 50 }),
  weeklyAvailableHours: integer('weekly_available_hours').default(10).notNull(),
  preferredStudyTimes: jsonb('preferred_study_times'), // e.g. [{ dayOfWeek: 1, start: '18:00', end: '20:00' }]
  strengths: jsonb('strengths'), // array of subject names/ids
  weaknesses: jsonb('weaknesses'), // array of subject names/ids
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

// 2. Study Plans
export const studyPlans = pgTable('study_plans', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').references(() => users.id, { onDelete: 'cascade' }).notNull(),
  title: varchar('title', { length: 255 }).notNull(),
  startDate: date('start_date').notNull(),
  endDate: date('end_date').notNull(),
  isActive: boolean('is_active').default(true).notNull(),
  metadata: jsonb('metadata'), // config options, goals, target subjects
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

// 3. Study Tasks
export const studyTasks = pgTable('study_tasks', {
  id: uuid('id').primaryKey().defaultRandom(),
  planId: uuid('plan_id').references(() => studyPlans.id, { onDelete: 'cascade' }).notNull(),
  userId: uuid('user_id').references(() => users.id, { onDelete: 'cascade' }).notNull(),
  subjectId: uuid('subject_id').references(() => subjects.id, { onDelete: 'set null' }),
  title: varchar('title', { length: 255 }).notNull(),
  description: varchar('description', { length: 1000 }),
  date: date('date').notNull(),
  scheduledStart: time('scheduled_start'),
  durationMinutes: integer('duration_minutes').notNull(),
  status: studyTaskStatusEnum('status').default('pending').notNull(),
  completedAt: timestamp('completed_at', { withTimezone: true }),
  scoreReceived: integer('score_received'), // if task represents a quiz/exam
  resourceType: varchar('resource_type', { length: 100 }), // e.g. 'file', 'exam', 'flashcard'
  resourceId: uuid('resource_id'),
  isAutoGenerated: boolean('is_auto_generated').default(true).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

// 4. Predictive Insights
export const predictiveInsights = pgTable('predictive_insights', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').references(() => users.id, { onDelete: 'cascade' }).notNull(),
  subjectId: uuid('subject_id').references(() => subjects.id, { onDelete: 'cascade' }).notNull(),
  predictedScore: decimal('predicted_score', { precision: 5, scale: 2 }),
  successProbability: decimal('success_probability', { precision: 5, scale: 2 }),
  riskLevel: riskLevelEnum('risk_level').notNull(),
  recommendations: jsonb('recommendations'), // list of suggested focus actions
  calculatedAt: timestamp('calculated_at', { withTimezone: true }).defaultNow().notNull(),
});

// 5. Study Recommendations
export const studyRecommendations = pgTable('study_recommendations', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').references(() => users.id, { onDelete: 'cascade' }).notNull(),
  subjectId: uuid('subject_id').references(() => subjects.id, { onDelete: 'cascade' }),
  type: recommendationTypeEnum('type').notNull(),
  title: varchar('title', { length: 255 }).notNull(),
  description: varchar('description', { length: 1000 }),
  resourceType: varchar('resource_type', { length: 100 }),
  resourceId: uuid('resource_id'),
  isApplied: boolean('is_applied').default(false).notNull(),
  scoreImportance: integer('score_importance').default(1).notNull(), // priority metric
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

// 6. Badges (Static Metadata)
export const badges = pgTable('badges', {
  id: uuid('id').primaryKey().defaultRandom(),
  code: varchar('code', { length: 100 }).unique().notNull(),
  name: varchar('name', { length: 255 }).notNull(),
  description: varchar('description', { length: 1000 }).notNull(),
  iconUrl: varchar('icon_url', { length: 500 }),
  xpReward: integer('xp_reward').default(0).notNull(),
});

// 7. User Badges (Many-to-Many Earned)
export const userBadges = pgTable('user_badges', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').references(() => users.id, { onDelete: 'cascade' }).notNull(),
  badgeId: uuid('badge_id').references(() => badges.id, { onDelete: 'cascade' }).notNull(),
  earnedAt: timestamp('earned_at', { withTimezone: true }).defaultNow().notNull(),
});

// 8. Challenges
export const challenges = pgTable('challenges', {
  id: uuid('id').primaryKey().defaultRandom(),
  title: varchar('title', { length: 255 }).notNull(),
  description: varchar('description', { length: 1000 }).notNull(),
  type: challengeTypeEnum('type').notNull(),
  targetValue: integer('target_value').notNull(), // e.g. minutes studied or cards reviewed
  xpReward: integer('xp_reward').notNull(),
  startDate: timestamp('start_date', { withTimezone: true }).notNull(),
  endDate: timestamp('end_date', { withTimezone: true }).notNull(),
});

// 9. User Challenges (Enrollment & Progress)
export const userChallenges = pgTable('user_challenges', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').references(() => users.id, { onDelete: 'cascade' }).notNull(),
  challengeId: uuid('challenge_id').references(() => challenges.id, { onDelete: 'cascade' }).notNull(),
  currentValue: integer('current_value').default(0).notNull(),
  isCompleted: boolean('is_completed').default(false).notNull(),
  completedAt: timestamp('completed_at', { withTimezone: true }),
});

// 10. Student Relations (Parent/Teacher Access)
export const studentRelations = pgTable('student_relations', {
  id: uuid('id').primaryKey().defaultRandom(),
  studentId: uuid('student_id').references(() => users.id, { onDelete: 'cascade' }).notNull(),
  guardianId: uuid('guardian_id').references(() => users.id, { onDelete: 'cascade' }).notNull(),
  relationType: relationTypeEnum('relation_type').notNull(),
  isApproved: boolean('is_approved').default(false).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

// Relations
export const studentProfilesRelations = relations(studentProfiles, ({ one }) => ({
  user: one(users, { fields: [studentProfiles.userId], references: [users.id] }),
}));

export const studyPlansRelations = relations(studyPlans, ({ one, many }) => ({
  user: one(users, { fields: [studyPlans.userId], references: [users.id] }),
  tasks: many(studyTasks),
}));

export const studyTasksRelations = relations(studyTasks, ({ one }) => ({
  plan: one(studyPlans, { fields: [studyTasks.planId], references: [studyPlans.id] }),
  user: one(users, { fields: [studyTasks.userId], references: [users.id] }),
  subject: one(subjects, { fields: [studyTasks.subjectId], references: [subjects.id] }),
}));

export const predictiveInsightsRelations = relations(predictiveInsights, ({ one }) => ({
  user: one(users, { fields: [predictiveInsights.userId], references: [users.id] }),
  subject: one(subjects, { fields: [predictiveInsights.subjectId], references: [subjects.id] }),
}));

export const studyRecommendationsRelations = relations(studyRecommendations, ({ one }) => ({
  user: one(users, { fields: [studyRecommendations.userId], references: [users.id] }),
  subject: one(subjects, { fields: [studyRecommendations.subjectId], references: [subjects.id] }),
}));

export const userBadgesRelations = relations(userBadges, ({ one }) => ({
  user: one(users, { fields: [userBadges.userId], references: [users.id] }),
  badge: one(badges, { fields: [userBadges.badgeId], references: [badges.id] }),
}));

export const userChallengesRelations = relations(userChallenges, ({ one }) => ({
  user: one(users, { fields: [userChallenges.userId], references: [users.id] }),
  challenge: one(challenges, { fields: [userChallenges.challengeId], references: [challenges.id] }),
}));

export const studentRelationsRelations = relations(studentRelations, ({ one }) => ({
  student: one(users, { fields: [studentRelations.studentId], references: [users.id], relationName: 'student' }),
  guardian: one(users, { fields: [studentRelations.guardianId], references: [users.id], relationName: 'guardian' }),
}));
